### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by amilajack** [vigneshshanmugam/optimize-js-plugin#5]
Would be nice if this project could feature tests.

**Comment by vigneshshanmugam** [comment]
@amilajack Will add it

**Comment by amilajack** [comment]
Naive implementation:

```
uglify-js some > test === webpack
```

😆

**Comment by vigneshshanmugam** [comment]
Ah ha that would be so simpler.  I was thinking of something similar to this https://github.com/nolanlawson/optimize-js/blob/master/test/test.js with webpack config output.

**Comment by amilajack** [comment]
Sounds good

**Comment by vigneshshanmugam** [comment]
addressed https://github.com/vigneshshanmugam/optimize-js-plugin/commit/89ed3bbb166041b29ea3586eae2d2e954680c37e
